server:
  port: 8080

spring:
  application:
    name: healthcare-api-gateway

  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:8086 #lb://PATIENT-SERVICE
          predicates:
              - Path=/api/v1/patient/**
#          filters:
#              - StripPrefix=2

        - id: appointment-service
          uri: http://localhost:8084  #lb://APPOINTMENT-SERVICE
          predicates:
            - Path=/api/v1/appointments/**
#          filters:
#            - StripPrefix=2

        - id: user-service
          uri: http://localhost:8085 #lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
#          filters:
#            - StripPrefix=2

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

services:
  user-service-url: "http://user-service/api/v1/users"

jwt:
  expiration: 1800000


public-api:
  paths: /auth/, /public/





