server:
   port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service-db
    username: postgres
    password: chamilaRoot@123$
    driver-class-name: org.postgresql.Driver
