server:
   port: 8084
   servlet:
     session:
       cookie:
         same-site: strict
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appointment-service-db
    username: postgres
    password: chamilaRoot@123$
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



